on:
  release:
    types: [created]
    
jobs:
  release:
    name: Release and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm install -g vsce
      - name: Publish to Marketplace
        run: vsce publish -p $PUBLISHER_TOKEN
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
